'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle, AlertCircle, PlayCircle, FileText } from 'lucide-react';
import Modal from '@/components/ui/Modal';
import Button from '@/components/ui/Button';
import styles from './LessonModal.module.css';

export default function LessonModal({ isOpen, onClose, nodeData }) {
    const [activeTab, setActiveTab] = useState('learn');
    const [selectedAnswer, setSelectedAnswer] = useState(null);
    const [isQuizSubmitted, setIsQuizSubmitted] = useState(false);

    if (!nodeData) return null;

    const { title, description, type } = nodeData;

    // Mock Content
    const lessonContent = {
        overview: "This is a brief overview of the topic generated by AI.",
        content: `
      Here is the detailed explanation for ${title}. 
      In a real application, this would be generated dynamically by an LLM 
      based on the user's specific progress and the node they clicked.
      
      We can use Markdown rendering here for rich text, code blocks, etc.
    `,
        videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ' // Dummy placeholder
    };

    const quizContent = {
        question: `What is the core principle behind ${title}?`,
        options: [
            { id: 'a', text: 'Option A: The first principle.' },
            { id: 'b', text: `Option B: The correct principle of ${title}.` },
            { id: 'c', text: 'Option C: Another plausible principle.' },
            { id: 'd', text: 'Option D: None of the above.' }
        ],
        correctAnswer: 'b'
    };

    const handleQuizSubmit = () => {
        setIsQuizSubmitted(true);
    };

    const renderLearnTab = () => (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className={styles.tabContent}
        >
            <p className={styles.intro}>{description}</p>

            <div className={styles.videoWrapper}>
                <div className={styles.videoPlaceholder}>
                    <PlayCircle size={48} className={styles.playIcon} />
                    <span>AI Generated Explainer Video</span>
                </div>
            </div>

            <div className={styles.article}>
                <h3>Key Takeaways</h3>
                <p>{lessonContent.content}</p>
            </div>

            <div className={styles.actions}>
                <Button onClick={() => setActiveTab('quiz')} variant="primary">
                    Take Quiz
                </Button>
            </div>
        </motion.div>
    );

    const renderQuizTab = () => (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className={styles.tabContent}
        >
            <div className={styles.quizHeader}>
                <h3>Knowledge Check</h3>
                <p>{quizContent.question}</p>
            </div>

            <div className={styles.optionsList}>
                {quizContent.options.map(opt => {
                    const isSelected = selectedAnswer === opt.id;
                    const isCorrect = opt.id === quizContent.correctAnswer;
                    const showResult = isQuizSubmitted;

                    let stateClass = '';
                    if (showResult) {
                        if (isCorrect) stateClass = styles.correct;
                        else if (isSelected) stateClass = styles.incorrect;
                    } else if (isSelected) {
                        stateClass = styles.selected;
                    }

                    return (
                        <button
                            key={opt.id}
                            className={`${styles.optionBtn} ${stateClass}`}
                            onClick={() => !showResult && setSelectedAnswer(opt.id)}
                            disabled={showResult}
                        >
                            <div className={styles.optionContent}>
                                <span className={styles.optionLabel}>{opt.id.toUpperCase()}</span>
                                <span>{opt.text}</span>
                            </div>
                            {showResult && isCorrect && <CheckCircle size={20} className={styles.successIcon} />}
                            {showResult && isSelected && !isCorrect && <AlertCircle size={20} className={styles.errorIcon} />}
                        </button>
                    )
                })}
            </div>

            <div className={styles.actions}>
                {!isQuizSubmitted ? (
                    <Button
                        onClick={handleQuizSubmit}
                        disabled={!selectedAnswer}
                        variant="gradient"
                    >
                        Submit Answer
                    </Button>
                ) : (
                    <Button onClick={onClose} variant="primary">
                        Continue Journey
                    </Button>
                )}
            </div>
        </motion.div>
    );

    return (
        <Modal isOpen={isOpen} onClose={onClose} title={title}>

            {type === 'topic' || type === 'lesson' ? (
                <div className={styles.tabs}>
                    <button
                        className={`${styles.tabBtn} ${activeTab === 'learn' ? styles.activeTab : ''}`}
                        onClick={() => setActiveTab('learn')}
                    >
                        <FileText size={16} /> Learn
                    </button>
                    <button
                        className={`${styles.tabBtn} ${activeTab === 'quiz' ? styles.activeTab : ''}`}
                        onClick={() => setActiveTab('quiz')}
                    >
                        <HelpCircle size={16} /> Practice
                    </button>
                </div>
            ) : null}

            <div className={styles.scrollArea}>
                <AnimatePresence mode="wait">
                    {type === 'quiz' || activeTab === 'quiz' ? (
                        <React.Fragment key="quiz">
                            {renderQuizTab()}
                        </React.Fragment>
                    ) : (
                        <React.Fragment key="learn">
                            {renderLearnTab()}
                        </React.Fragment>
                    )}
                </AnimatePresence>
            </div>
        </Modal>
    );
}

// Need to import HelpCircle locally to avoid circularity issues in some setups
import { HelpCircle } from 'lucide-react';
